server:
  port: 8083
eureka:
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
spring:
  application:
    name: discovery-service
